#!/bin/sh
set -e
DIR=${DIR:-appliances}

if [ -n "$1" ]; then
  METADATA_FILE="$1"
else
  METADATA_FILE="./metadata"
fi

case "$1" in
  http*)
    METADATA="$(curl -sS "$METADATA_FILE")"
  ;;
  *)
    METADATA="$(cat "$METADATA_FILE")"
  ;;
esac

echo "Processing appliances"
mkdir -p "$DIR"

echo "$METADATA" | while read line; do
  APP="$(echo "$line" | awk -F\" '{print $2}' | base64 -d)"
  NAME=$(echo "$APP" | sed -n 's/^NAME="\(.*\)"$/\1/p' | tr ' ' '_')
  PUBLISHER=$(echo "$APP" | sed -n 's/^PUBLISHER="\(.*\)"$/\1/p' | tr ' ' '_')
  APPTEMPLATE64=$(echo "$APP" | sed -n 's/^APPTEMPLATE64="\(.*\)"$/\1/p' | base64 -d)
  VMTEMPLATE64=$(echo "$APP" | sed -n 's/^VMTEMPLATE64="\(.*\)"$/\1/p' | base64 -d)
  if [ "$PUBLISHER" = "OpenNebula_Systems" ]; then

    HYPERVISOR=$(echo "$APP" | sed -n 's/^NAME=".*- \(.*\)"$/\1/p' | tr '[:upper:]' '[:lower:]' )
    [ -n "$HYPERVISOR" ] || HYPERVISOR=kvm
    APPLIANCE_DIR="$DIR/$PUBLISHER/$HYPERVISOR/$NAME"
  else
    APPLIANCE_DIR="$DIR/$PUBLISHER/$NAME"
  fi
  echo "$APPLIANCE_DIR"
  mkdir -p "$APPLIANCE_DIR"
  if [ -n "$APPTEMPLATE64" ]; then
    echo "$APPTEMPLATE64" > "$APPLIANCE_DIR/apptemplate.conf"
    APP=$(echo "$APP" | sed '/^APPTEMPLATE64=/d')
  fi
  if [ -n "$VMTEMPLATE64" ]; then
    echo "$VMTEMPLATE64" > "$APPLIANCE_DIR/vmtemplate.conf"
    APP=$(echo "$APP" | sed '/^VMTEMPLATE64=/d')
  fi
  echo "$APP" > "$APPLIANCE_DIR/app.conf"
done
