#!/bin/bash
APPLIANCES_DIR="$(dirname $0)/data/appliances/"
curl -L https://github.com/OpenNebula/marketplace/archive/master.tar.gz | tar -xzf - -C /tmp
mkdir -p "$APPLIANCES_DIR"
APPLIANCES_ORIG=$(find /tmp/marketplace-master -name '*.yaml')
sed -i 's|^logo: |logo: https://raw.githubusercontent.com/OpenNebula/marketplace/master/logos/|g' $APPLIANCES_ORIG
mv $APPLIANCES_ORIG "$APPLIANCES_DIR"
rm -rf /tmp/marketplace-master
